name = "plant-tracker-d1"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "plant-tracker-db"
database_id = "93f0cc05-166d-474c-b9ef-1d68ca1ce135"
